// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHazZZyV1cb_Uk5kjrVS-GpB8Jz05zCk',
    appId: '1:798075529176:web:4f3d07f2e72bed227b74ad',
    messagingSenderId: '798075529176',
    projectId: 'flutterfirebasedemo-ad9b6',
    authDomain: 'flutterfirebasedemo-ad9b6.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-ad9b6.firebasestorage.app',
    measurementId: 'G-J24F777NJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu4losNredhtOj6Z_g39Kj0v6BRvQFYu4',
    appId: '1:798075529176:android:a8cf9b7424bad0687b74ad',
    messagingSenderId: '798075529176',
    projectId: 'flutterfirebasedemo-ad9b6',
    storageBucket: 'flutterfirebasedemo-ad9b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs0rdUz41t22iAEjOQOBP_8uL4PgAQ3jw',
    appId: '1:798075529176:ios:f03b455369a4f9577b74ad',
    messagingSenderId: '798075529176',
    projectId: 'flutterfirebasedemo-ad9b6',
    storageBucket: 'flutterfirebasedemo-ad9b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs0rdUz41t22iAEjOQOBP_8uL4PgAQ3jw',
    appId: '1:798075529176:ios:f03b455369a4f9577b74ad',
    messagingSenderId: '798075529176',
    projectId: 'flutterfirebasedemo-ad9b6',
    storageBucket: 'flutterfirebasedemo-ad9b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHazZZyV1cb_Uk5kjrVS-GpB8Jz05zCk',
    appId: '1:798075529176:web:fd3db16b5f1f2fc97b74ad',
    messagingSenderId: '798075529176',
    projectId: 'flutterfirebasedemo-ad9b6',
    authDomain: 'flutterfirebasedemo-ad9b6.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-ad9b6.firebasestorage.app',
    measurementId: 'G-RX6ZGKKSJ2',
  );
}
